- name: Add backup scripts dir
  ansible.builtin.file:
    path: /etc/backup-scripts
    state: directory
    mode: "0755"
- name: Add backup files dir
  ansible.builtin.file:
    path: /var/lib/backup
    state: directory
    mode: "700"
- name: Add backup-b32-1 key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'backup-b32-1.pub') }}"
    key_options: 'from="10.5.0.247,2001:630:d0:f700::247"'  # yamllint disable-line rule:quoted-strings
- name: Add backup-b53-1 key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'backup-b53-1.pub') }}"
    key_options: 'from="10.5.0.248,2001:630:d0:f700::248"'  # yamllint disable-line rule:quoted-strings
- name: Get package facts
  ansible.builtin.package_facts:
    manager: auto
- name: Configure mysql backups
  import_tasks: mysql.yml
  when: >
     "mysql-server" in ansible_facts.packages or
     "mariadb-server" in ansible_facts.packages
